version: '3.7'
services:
  golang-middleware:
    build:
      context: ./template/golang-middleware
      target: build
    ports:
      - "8081:8080"
    environment:
      fprocess: air -c /go/src/handler/function/.air.toml
      mode: http
      upstream_url: http://127.0.0.1:8082
    volumes:
      - ./timesheet-calculator:/go/src/handler/function
      - ./secrets/:/var/openfaas/secrets
    command: sh -c "go install github.com/cosmtrek/air@latest && fwatchdog"
