version: 1.0
provider:
  name: openfaas
  gateway: https://openfaas.k3s.dansult.space
functions:
  links:
    lang: python3
    handler: ./links
    image: docker.io/danielmichaels/links:latest
    environment:
      content_type: text/html
